language: ruby

rvm:
  - 2.4.1

sudo: required

before_install:
  - sudo update-ca-certificates

script:
  - bundle exec rake

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
