title: albinek.com
description: "Mostly thoughts about IT stuff. Short answers for sophisticated questions."
year: 2017

author:
  name: "Albin &quot;albinek&quot; Sadowski"
  email: "albinek@albinek.com"
  url: "http://albinek.com"

github:
  username: albinekcom

twitter:
  username: albinekcom

linkedin:
  username: albinekcom

facebook:
  username: albinekcom

snapchat:
  username: albinekcom

google:
  analytics: UA-80395419-1

disqus:
  shortname: albinekcom

permalink: /:title
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo/albinek.com.png

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md
  - Rakefile

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  style: compressed
