title: albinek.com
email: albinek@albinek.com
description: "Mostly thoughts about IT stuff."
baseurl: ""
url: "http://albinek.com"
twitter_username: albinekcom
github_username: albinekcom

google_analytics: UA-80395419-1
disqus:
  shortname: albinekcom
permalink: /:title
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - octopress-minify-html
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
