title: albinek.com
description: "Mostly thoughts about IT stuff."
baseurl: ""

author:
  name: "Albinek \"albinek\" Sadowski"
  email: "albinek@albinek.com"
  url: "http://albinek.com"

twitter:
  username: albinekcom

github:
  username: albinekcom

google_analytics: UA-80395419-1

disqus:
  shortname: albinekcom

permalink: /:title
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md
  - Rakefile

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  style: compressed
